### ISSUE TITLE
scenes.csv misannotation

### ISSUE THREAD

**Issue by AlonDaks** [hanke/gumpdata#2]
Hi @hanke 

In scenes, the row 5507.0,"RIVERSIDE","NIGHT","DAY" is mislabeled in the interior / exterior (4th column). Do you know what the correct annotation should be?

Thank you,
Alon

**Comment by mih** [comment]
Thanks for your report. I fixed the annotation (DAY->EXT).

Moreover, please use this scene annotation file (more precise, hand-checked timing):
https://github.com/psychoinformatics-de/paper-f1000_gumpemotions/blob/master/data/movie_scenes.csv

And dedicated repository with all existing annotations will be published shortly.

**Comment by AlonDaks** [comment]
Thank you for the quick correction and the more annotated file.

**Comment by mih** [comment]
FTR: Here is the new place to gather all available annotations.

https://github.com/psychoinformatics-de/studyforrest_annotations
